// Flux2Pipeline+ChainHelpers.swift — Public hooks for Flux2Chains
// Copyright 2025 Vincent Gourbin
//
// Minimal access surface for chain extensions living in the `Flux2Chains`
// library. Anything more invasive (custom denoising loops, etc.) belongs in
// `Flux2Pipeline.swift` proper.

import Foundation
import MLX
import CoreGraphics

/// How a `CGImage` should be interpreted as a RePaint inpainting mask.
///
/// Two distinct conventions are supported so callers can pick whichever
/// matches their authoring workflow:
///
/// - ``grayscaleWhiteInpaint`` — the legacy, source-separated mask. The
///   caller supplies a **separate** grayscale image where bright pixels
///   tell the chain to repaint. Best when the mask is generated by an
///   algorithm (segmentation network, threshold, …) that already emits a
///   single-channel image.
///
/// - ``alphaTransparentInpaint`` — the "erased image" mask. The caller
///   supplies a **copy of the source image with the to-replace region
///   erased to transparency**. The chain reads the alpha channel only and
///   ignores the RGB content. Best for hand-authored masks in Photoshop /
///   Affinity / Procreate where the natural gesture is the eraser tool.
///
/// Both are equivalent expressiveness-wise (soft values supported in both
/// directions); pick the one that doesn't force you to maintain two files
/// in lockstep.
public enum Flux2MaskConvention: Sendable, Equatable {
    /// Grayscale luminance reading. White (255) = inpaint, black (0) = keep.
    /// Soft greys in between are honoured (use a Gaussian blur on the mask
    /// edge for a seamless transition).
    ///
    /// The RGB content of the input is used (alpha is ignored). If the
    /// input has no alpha and is single-channel grayscale, this is the
    /// direct path.
    case grayscaleWhiteInpaint
    /// Alpha-channel reading. Transparent (alpha = 0) = inpaint, opaque
    /// (alpha = 255) = keep. Soft alpha values are preserved as soft mask
    /// values (so feathered erasers work end-to-end).
    ///
    /// The RGB content of the input is **ignored** — the chain reads the
    /// alpha plane only. This matches the natural "erase the bit you want
    /// to redo" workflow without forcing you to also maintain a separate
    /// grayscale companion file: pass the same image you're inpainting,
    /// but with the to-replace region erased to transparency.
    case alphaTransparentInpaint
}

extension Flux2Pipeline {

    // MARK: - Image ↔ latent

    /// Encode a `CGImage` to packed-sequence latents `[1, (h/16)*(w/16), 128]`,
    /// already normalised with the VAE BatchNorm statistics so the tensor is
    /// directly comparable with the denoiser's working latents.
    ///
    /// Used by chains that need access to the original-image latent (e.g.
    /// `Flux2MaskedInpaintingChain` for RePaint-style per-step blending).
    /// Loads the VAE on demand and keeps it resident — the subsequent
    /// `generateWithResult` call will reuse it.
    ///
    /// - Parameters:
    ///   - image: Source image.
    ///   - targetHeight: Target output height in pixels (must be a multiple of 32).
    ///   - targetWidth: Target output width in pixels (must be a multiple of 32).
    ///   - samplePosterior: When `true`, sample from the VAE posterior; when
    ///     `false`, use the deterministic mean (default — matches the existing
    ///     I2I path).
    /// - Returns: Packed-sequence latents ready to be blended with the
    ///   denoising state inside a `Flux2StepHook`.
    public func encodeImageToPackedSequence(
        _ image: CGImage,
        targetHeight: Int,
        targetWidth: Int,
        samplePosterior: Bool = false
    ) async throws -> MLXArray {
        try await ensureVAELoaded()
        guard let vae = vaeForChains else {
            throw Flux2Error.modelNotLoaded("VAE")
        }

        let preprocessed = await preprocessImageForVAEPublic(
            image,
            targetHeight: targetHeight,
            targetWidth: targetWidth
        )
        let rawLatents = vae.encode(preprocessed, samplePosterior: samplePosterior)
        var patchified = LatentUtils.packLatentsToPatchified(rawLatents)
        patchified = LatentUtils.normalizeLatentsWithBatchNorm(
            patchified,
            runningMean: vae.batchNormRunningMean,
            runningVar: vae.batchNormRunningVar
        )
        let packed = LatentUtils.packPatchifiedToSequence(patchified)
        eval(packed)
        return packed
    }

    // MARK: - Dimensions & mask helpers

    /// Clamp `(width, height)` to the nearest lower multiple of 32 within
    /// `maxPixels` pixels — the layout the FLUX.2 transformer expects.
    ///
    /// - Parameters:
    ///   - width: Requested output width.
    ///   - height: Requested output height.
    ///   - maxPixels: Maximum total pixel count (default 1024² ≈ 1 048 576).
    public static func resolveChainDimensions(
        width: Int,
        height: Int,
        maxPixels: Int = 1024 * 1024
    ) -> (height: Int, width: Int) {
        let multipleOf = 32
        var w = width
        var h = height
        let pixelCount = w * h
        if pixelCount > maxPixels {
            let scale = (Double(maxPixels) / Double(pixelCount)).squareRoot()
            w = Int(Double(w) * scale)
            h = Int(Double(h) * scale)
        }
        w = max(multipleOf, (w / multipleOf) * multipleOf)
        h = max(multipleOf, (h / multipleOf) * multipleOf)
        return (height: h, width: w)
    }

    /// Rasterise a mask `CGImage` into a packed-sequence-aligned
    /// `[1, seq, 1]` MLX array suitable for broadcasting against
    /// `[1, seq, 128]` latents.
    ///
    /// The output is always in the chain's internal convention:
    /// `1.0` = **inpaint** (the model is allowed to write here),
    /// `0.0` = **keep** (the original-image latent is forced back at every
    /// step). Soft values in `[0, 1]` are preserved — pre-binarise yourself
    /// if you want hard edges.
    ///
    /// The way the input is read depends on ``convention``:
    /// - ``Flux2MaskConvention/grayscaleWhiteInpaint`` (default, back-compat):
    ///   reads luminance, white → inpaint.
    /// - ``Flux2MaskConvention/alphaTransparentInpaint``: reads the alpha
    ///   plane and inverts it, transparent → inpaint. RGB is ignored, so
    ///   callers can pass an "erased copy of the source image" instead of
    ///   maintaining a separate grayscale file.
    public static func packMaskForLatentBlending(
        _ mask: CGImage,
        targetHeight: Int,
        targetWidth: Int,
        convention: Flux2MaskConvention = .grayscaleWhiteInpaint
    ) async -> MLXArray {
        let latentH = targetHeight / 16
        let latentW = targetWidth / 16
        switch convention {
        case .grayscaleWhiteInpaint:
            return await packGrayscaleMask(mask, latentH: latentH, latentW: latentW)
        case .alphaTransparentInpaint:
            return await packAlphaMask(mask, latentH: latentH, latentW: latentW)
        }
    }

    private static func packGrayscaleMask(
        _ mask: CGImage, latentH: Int, latentW: Int
    ) async -> MLXArray {
        let count = latentH * latentW
        // The CGContext keeps a raw pointer into `pixels`; capturing it by
        // value into a Sendable closure isn't possible. The work item runs
        // synchronously inside the continuation and the await blocks until
        // it completes, so `UnsafeMutableBufferPointer` ownership stays
        // local — safe under the explicit happens-before.
        let floats: [Float] = await Self.runAtDefaultQoS {
            let buf = UnsafeMutablePointer<UInt8>.allocate(capacity: count)
            buf.initialize(repeating: 0, count: count)
            defer {
                buf.deinitialize(count: count)
                buf.deallocate()
            }
            let colorSpace = CGColorSpaceCreateDeviceGray()
            guard let context = CGContext(
                data: buf,
                width: latentW,
                height: latentH,
                bitsPerComponent: 8,
                bytesPerRow: latentW,
                space: colorSpace,
                bitmapInfo: CGImageAlphaInfo.none.rawValue
            ) else {
                return [Float](repeating: 0, count: count)
            }
            context.interpolationQuality = .high
            context.draw(mask, in: CGRect(x: 0, y: 0, width: latentW, height: latentH))
            return (0..<count).map { Float(buf[$0]) / 255.0 }
        }
        return MLXArray(floats).reshaped([1, count, 1])
    }

    private static func packAlphaMask(
        _ mask: CGImage, latentH: Int, latentW: Int
    ) async -> MLXArray {
        // We need the alpha channel only. Rendering into a premultipliedLast
        // RGBA8 context with the colourspace fully neutral and then sampling
        // byte index 3 gives the unmolested alpha value (premultiplication
        // doesn't apply when src alpha is reconstructed from byte 3, since
        // the destination starts cleared and we only read the alpha plane).
        let count = latentH * latentW
        let rgbaCount = count * 4
        let floats: [Float] = await Self.runAtDefaultQoS {
            let buf = UnsafeMutablePointer<UInt8>.allocate(capacity: rgbaCount)
            buf.initialize(repeating: 0, count: rgbaCount)
            defer {
                buf.deinitialize(count: rgbaCount)
                buf.deallocate()
            }
            let colorSpace = CGColorSpaceCreateDeviceRGB()
            guard let context = CGContext(
                data: buf,
                width: latentW,
                height: latentH,
                bitsPerComponent: 8,
                bytesPerRow: latentW * 4,
                space: colorSpace,
                bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
            ) else {
                return [Float](repeating: 0, count: count)
            }
            context.interpolationQuality = .high
            context.draw(mask, in: CGRect(x: 0, y: 0, width: latentW, height: latentH))
            // Invert: alpha=0 (transparent) → 1.0 (inpaint); alpha=255 → 0.0 (keep).
            return (0..<count).map { i in
                1.0 - Float(buf[i * 4 + 3]) / 255.0
            }
        }
        return MLXArray(floats).reshaped([1, count, 1])
    }
}
