// LoRAEvaluator.swift - Automated LoRA training evaluation pipeline
// Copyright 2025 Vincent Gourbin

import Foundation
import MLX
import FluxTextEncoders
import CoreGraphics
import ImageIO

// MARK: - Evaluation Results

/// LoRA training context — what the user wants to teach the model
public struct LoRAContext: Sendable {
    /// Short name for the training (e.g., "Cat Toy", "My Art Style")
    public let name: String
    /// Description of what the LoRA should learn (e.g., "A specific hand-painted wooden cat figurine")
    public let description: String

    public init(name: String, description: String) {
        self.name = name
        self.description = description
    }
}

/// Result of LoRA evaluation pipeline
public struct LoRAEvaluation: @unchecked Sendable {
    // Input
    public let referenceImage: CGImage
    public let context: LoRAContext

    // VLM analysis
    public let prompt: String                // Description used for baseline generation
    public let triggerWord: String            // Auto-suggested trigger word
    public let dopRecommended: Bool           // Whether DOP is recommended
    public let dopClass: String?              // DOP class if recommended

    // Generated baseline
    public let baselineImage: CGImage

    // Comparison scores
    public let sceneScore: Int
    public let styleScore: Int
    public let sceneReason: String
    public let styleReason: String

    // Training recommendation
    public let recommendation: LoRARecommendation
}

/// Recommended LoRA training parameters based on evaluation
public struct LoRARecommendation: Sendable {
    public let steps: Int
    public let rank: Int
    public let alpha: Float
    public let learningRate: Float
    public let warmupSteps: Int
    public let timestepSampling: String
    public let lossWeighting: String
    public let targetLayers: String
    public let useDOP: Bool
    public let dopClass: String?
    public let useGradientCheckpointing: Bool
    public let summary: String

    /// Export as YAML training config
    public func toYAML(model: Flux2Model, triggerWord: String, datasetPath: String = "./dataset") -> String {
        var yaml = """
        # LoRA Training Config — Auto-generated by evaluate-lora
        # \(summary)

        model:
          name: \(model.rawValue)
          quantization: bf16

        lora:
          rank: \(rank)
          alpha: \(alpha)
          target_layers: \(targetLayers)

        training:
          batch_size: 1
          max_steps: \(steps)
          warmup_steps: \(warmupSteps)
          learning_rate: \(learningRate)
          weight_decay: 0.0001

        loss:
          weighting: \(lossWeighting)
          timestep_sampling: \(timestepSampling)
        """

        if useDOP {
            yaml += "\n  diff_output_preservation: true"
            if let cls = dopClass {
                yaml += "\n  diff_output_preservation_class: \"\(cls)\""
            }
            yaml += "\n  diff_output_preservation_multiplier: 1.0"
        }

        yaml += """


        memory:
          gradient_checkpointing: \(useGradientCheckpointing)
          cache_latents: true
          cache_text_embeddings: true
          bucketing:
            enabled: true
            resolutions: [512, 768]

        dataset:
          path: \(datasetPath)
          trigger_word: \(triggerWord)
        """

        return yaml
    }
}

// MARK: - Evaluator

/// Automated LoRA training evaluation pipeline
/// Analyzes a reference image, generates a baseline with the base model,
/// compares them, and recommends training parameters.
public class LoRAEvaluator {

    public init() {}

    /// Run the full evaluation pipeline
    /// - Parameters:
    ///   - referenceImage: The target image to train towards
    ///   - model: Which FLUX.2 model to evaluate (klein-4b, klein-9b, dev)
    ///   - quantization: Quantization config for inference
    ///   - seed: Random seed for reproducible baseline generation
    ///   - width: Baseline image width
    ///   - height: Baseline image height
    ///   - hfToken: HuggingFace token for gated models
    ///   - onProgress: Progress callback
    public func evaluate(
        referenceImage: CGImage,
        context: LoRAContext,
        model: Flux2Model,
        quantization: Flux2QuantizationConfig = .init(textEncoder: .mlx8bit, transformer: .qint8),
        seed: UInt64 = 42,
        width: Int = 512,
        height: Int = 512,
        hfToken: String? = nil,
        onProgress: (@Sendable (String) -> Void)? = nil
    ) async throws -> LoRAEvaluation {

        // === Step 1: VLM analyzes reference image with LoRA context ===
        onProgress?("[1/5] Analyzing reference image with VLM...")
        onProgress?("  LoRA context: \"\(context.name)\" — \(context.description)")

        // Load VLM if not already loaded
        if !FluxTextEncoders.shared.isQwen35VLMLoaded {
            onProgress?("  Loading Qwen3.5 VLM...")
            let downloader = TextEncoderModelDownloader()
            let vlmPath = try await downloader.downloadQwen35(variant: .qwen35_4B_4bit)
            try await FluxTextEncoders.shared.loadQwen35VLM(from: vlmPath.path)
        }

        // Describe the image with LoRA context for focused description
        let descResult = try FluxTextEncoders.shared.describeImageForFlux(
            image: referenceImage,
            context: "This image is a training reference for a LoRA called \"\(context.name)\". Training goal: \(context.description). Describe the image focusing on what makes this subject unique and what the model needs to learn."
        )
        let description = descResult.text
        onProgress?("  Description: \"\(description.prefix(80))...\"")

        // === Step 2: LLM analyzes LoRA context for trigger word and DOP ===
        onProgress?("[2/5] Analyzing LoRA training context...")

        let analysisResult = try analyzeLoRAContext(context: context)
        onProgress?("  Trigger word: \(analysisResult.triggerWord)")
        onProgress?("  DOP: \(analysisResult.dopRecommended ? "yes (\(analysisResult.dopClass ?? "object"))" : "no")")

        // Unload VLM to free memory for generation
        FluxTextEncoders.shared.unloadQwen35VLM()
        Memory.clearCache()

        // === Step 3: Generate baseline image with base model ===
        onProgress?("[3/5] Generating baseline image (\(width)x\(height), seed=\(seed))...")

        let pipeline = Flux2Pipeline(
            model: model,
            quantization: quantization,
            vaeVariant: .smallDecoder,
            hfToken: hfToken
        )

        let steps = model.defaultSteps
        let guidance = model.defaultGuidance

        let baselineImage = try await pipeline.generateTextToImage(
            prompt: description,
            height: height,
            width: width,
            steps: steps,
            guidance: guidance,
            seed: seed
        ) { current, total in
            onProgress?("  Step \(current)/\(total)")
        }

        // Unload pipeline to free memory for VLM comparison
        // (pipeline deallocates when it goes out of scope, but let's be explicit)
        Memory.clearCache()

        // === Step 4: VLM compares reference vs baseline with LoRA focus ===
        onProgress?("[4/5] Comparing reference vs baseline...")

        // Reload VLM
        if !FluxTextEncoders.shared.isQwen35VLMLoaded {
            let downloader = TextEncoderModelDownloader()
            let vlmPath = try await downloader.downloadQwen35(variant: .qwen35_4B_4bit)
            try await FluxTextEncoders.shared.loadQwen35VLM(from: vlmPath.path)
        }

        // Contextual comparison — focused on what the LoRA needs to learn
        let comparisonSystemPrompt = """
        You compare two images for FLUX.2 LoRA training evaluation.
        Image 1 is the REFERENCE (target). Image 2 is what the base model generated WITHOUT any LoRA.

        TRAINING CONTEXT: "\(context.name)" — \(context.description)

        Score each criterion from 0 to 100. Be STRICT — the scores determine training intensity.

        SCENE score (content fidelity, 0-100):
        - 90-100: Identical subjects, exact same distinctive features, poses, details
        - 70-89: Same subjects but differences in specific features that the LoRA needs to learn
        - 50-69: Similar concept but missing key distinctive elements from the training context
        - 30-49: Same general category but substantially different from the specific subject
        - 0-29: Completely different subject

        STYLE score (visual fidelity, 0-100):
        - 90-100: Identical art style, line work, color palette, lighting, textures
        - 70-89: Same style family, minor execution differences
        - 50-69: Similar approach but clearly different rendering technique
        - 30-49: Different style categories
        - 0-29: Completely different visual style

        Respond ONLY with this exact JSON format, no other text:
        {"scene_score": N, "scene_reason": "what the LoRA needs to learn", "style_score": N, "style_reason": "what differs in style"}
        """

        guard let vlm = FluxTextEncoders.shared.qwen35VLMForEvaluation else {
            throw Flux2Error.modelNotLoaded("Qwen3.5 VLM not loaded")
        }

        let compResult = try vlm.generateMultiImage(
            images: [referenceImage, baselineImage],
            prompt: "Compare these two images for LoRA training evaluation.",
            systemPrompt: comparisonSystemPrompt,
            enableThinking: false,
            maxTokens: 300,
            temperature: 0
        )

        let comparison = FluxTextEncoders.shared.parseComparisonForEvaluation(compResult.text)

        onProgress?("  Scene: \(comparison.sceneScore)/100 — \(comparison.sceneReason)")
        onProgress?("  Style: \(comparison.styleScore)/100 — \(comparison.styleReason)")

        // Unload VLM
        FluxTextEncoders.shared.unloadQwen35VLM()

        // === Step 5: Generate recommendation ===
        onProgress?("[5/5] Generating training recommendation...")

        let recommendation = computeRecommendation(
            sceneScore: comparison.sceneScore,
            styleScore: comparison.styleScore,
            model: model,
            dopRecommended: analysisResult.dopRecommended,
            dopClass: analysisResult.dopClass
        )

        onProgress?("  \(recommendation.summary)")

        return LoRAEvaluation(
            referenceImage: referenceImage,
            context: context,
            prompt: description,
            triggerWord: analysisResult.triggerWord,
            dopRecommended: analysisResult.dopRecommended,
            dopClass: analysisResult.dopClass,
            baselineImage: baselineImage,
            sceneScore: comparison.sceneScore,
            styleScore: comparison.styleScore,
            sceneReason: comparison.sceneReason,
            styleReason: comparison.styleReason,
            recommendation: recommendation
        )
    }

    // MARK: - LoRA Context Analysis

    private struct ContextAnalysis {
        let triggerWord: String
        let dopRecommended: Bool
        let dopClass: String?
    }

    /// Use LLM to analyze the LoRA context and suggest trigger word + DOP settings
    private func analyzeLoRAContext(context: LoRAContext) throws -> ContextAnalysis {
        let analysisPrompt = """
        TASK: Analyze this LoRA training description and provide recommendations.

        TRAINING NAME: "\(context.name)"
        DESCRIPTION: "\(context.description)"

        CONTEXT:
        - A LoRA teaches an AI image generator a new concept
        - A "trigger word" is a unique word that activates the LoRA in prompts (e.g., "ohwx", "sks")
        - DOP (Differential Output Preservation) helps preserve the general class while learning specific features
        - DOP is useful when training a specific instance of a category (e.g., a specific person, a specific object)
        - DOP requires knowing the "class" (e.g., "woman", "man", "cat", "dog", "car", "toy")

        OUTPUT FORMAT: Valid JSON only, no markdown, no explanation.
        {"trigger_word": "xyz_name", "dop_recommended": true, "dop_class": "cat"}
        """

        let result = try FluxTextEncoders.shared.generateWithQwen35(
            prompt: analysisPrompt,
            systemPrompt: "You are a LoRA training configuration assistant. Output only valid JSON.",
            maxTokens: 100,
            temperature: 0
        )

        // Parse JSON from response
        let text = result.text
        if let start = text.firstIndex(of: "{"), let end = text.lastIndex(of: "}") {
            let jsonStr = String(text[start...end])
            struct Analysis: Decodable {
                let trigger_word: String?
                let dop_recommended: Bool?
                let dop_class: String?
            }
            if let data = jsonStr.data(using: .utf8),
               let parsed = try? JSONDecoder().decode(Analysis.self, from: data) {
                return ContextAnalysis(
                    triggerWord: parsed.trigger_word ?? "sks",
                    dopRecommended: parsed.dop_recommended ?? false,
                    dopClass: parsed.dop_class
                )
            }
        }

        // Fallback
        return ContextAnalysis(triggerWord: "sks", dopRecommended: false, dopClass: nil)
    }

    // MARK: - Recommendation Logic

    private func computeRecommendation(sceneScore: Int, styleScore: Int, model: Flux2Model, dopRecommended: Bool, dopClass: String?) -> LoRARecommendation {
        // Scores are now 0-100
        let sceneGap = 100 - max(0, min(100, sceneScore))
        let styleGap = 100 - max(0, min(100, styleScore))
        let avgGap = (sceneGap + styleGap) / 2
        let needsGradientCheckpoint = model == .dev || model == .klein9B || model == .klein9BBase

        // Steps and rank based on average gap (0-100 scale)
        // Minimum rank 32 — anything lower doesn't have enough capacity for meaningful LoRA training
        let steps: Int
        let rank: Int

        switch avgGap {
        case 0...10:   // Almost identical (both 90+)
            steps = 250; rank = 32
        case 11...20:  // Very close (both 80+)
            steps = 500; rank = 32
        case 21...35:  // Moderate gap
            steps = 1000; rank = 32
        case 36...50:  // Significant gap
            steps = 1500; rank = 48
        default:       // Large gap (50+)
            steps = 2000; rank = 64
        }

        // Timestep sampling based on which dimension needs more work
        let timestepSampling: String
        if sceneGap > styleGap + 15 {
            timestepSampling = "content"  // Focus on subjects/objects
        } else if styleGap > sceneGap + 15 {
            timestepSampling = "style"    // Focus on visual style
        } else {
            timestepSampling = "balanced" // Both need work
        }

        // DOP from context analysis + scene gap
        let useDOP = dopRecommended || sceneGap >= 30

        // Target layers — always "all" for rank <= 48 (enough memory)
        let targetLayers = rank <= 48 ? "all" : "attention"

        // Summary
        let sceneLabel = sceneGap <= 10 ? "LOW" : (sceneGap <= 30 ? "MODERATE" : "HIGH")
        let styleLabel = styleGap <= 10 ? "LOW" : (styleGap <= 30 ? "MODERATE" : "HIGH")
        let summary = "Scene gap: \(sceneLabel) (\(sceneScore)/100), Style gap: \(styleLabel) (\(styleScore)/100) → \(steps) steps, rank \(rank), \(timestepSampling) sampling"

        return LoRARecommendation(
            steps: steps,
            rank: rank,
            alpha: Float(rank),
            learningRate: 1e-4,
            warmupSteps: max(10, steps / 10),
            timestepSampling: timestepSampling,
            lossWeighting: "bell_shaped",
            targetLayers: targetLayers,
            useDOP: useDOP,
            dopClass: dopClass,
            useGradientCheckpointing: needsGradientCheckpoint,
            summary: summary
        )
    }
}
